import {
  Baby,
  BookOpen,
  Briefcase,
  Car,
  Coffee,
  Dumbbell,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Music,
  PawPrint,
  Pill,
  Plane,
  Popcorn,
  Scissors,
  Shirt,
  ShoppingCart,
  Smartphone,
  Tag,
  Tv,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  popcorn: Popcorn,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  shirt: Shirt,
  home: Home,
  briefcase: Briefcase,
  tag: Tag,
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  music: Music,
  plane: Plane,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  pill: Pill,
  gift: Gift,
  wallet: Wallet,
  tv: Tv,
  smartphone: Smartphone,
  baby: Baby,
  "paw-print": PawPrint,
  scissors: Scissors,
  zap: Zap,
};

export const ICON_NAMES = Object.keys(CATEGORY_ICONS);
